# Generated by Django 3.2.4 on 2022-12-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=120)),
                ('avatar', models.ImageField(upload_to='avatar/%Y')),
                ('loginby', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('shippingmobile', models.CharField(default='', max_length=15)),
                ('shippingname', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('zalo', models.CharField(default='', max_length=15)),
                ('social', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
