# Generated by Django 3.2.4 on 2022-12-04 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customeruser_iduser'),
        ('products', '0007_auto_20221204_1227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('shippingmobile', models.CharField(default='', max_length=15)),
                ('shippingname', models.CharField(blank=True, max_length=255)),
                ('payment_method', models.IntegerField(choices=[(0, 'COD'), (1, 'Bank')], default=0)),
                ('address', models.CharField(default='', max_length=255)),
                ('shippingfee', models.IntegerField(default=0)),
                ('deivered_date', models.DateTimeField(auto_now_add=True)),
                ('idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customeruser')),
                ('idstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.statusorder')),
                ('iduser', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanlity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('idorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.course')),
            ],
        ),
    ]
