# Generated by Django 4.1.3 on 2022-12-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
