# Generated by Django 4.1.3 on 2022-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_course_price_variation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="inventory",
        ),
        migrations.AddField(
            model_name="course",
            name="inventory",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="star",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="discount_from_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="discount_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="variation",
            name="discount_to_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
