# Generated by Django 4.1.3 on 2022-12-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_variation_inventory_course_inventory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="star",
            field=models.FloatField(default=0),
        ),
    ]
