# Generated by Django 3.2.4 on 2022-12-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_course_inventory_alter_course_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(default=500000),
        ),
    ]
